development:
  adapter: postgresql
  encoding: unicode
  database: metis_devel
  pool: 5
  username: foo
  password: bar

test:
  adapter: postgresql
  encoding: unicode
  database: metis_test
  pool: 5
  username: foo
  password: bar

production:
  adapter: postgresql
  encoding: unicode
  database: metis_prod
  host: localhost
  pool: 5
  username: foo
  password: bar
